### ISSUE TITLE
Building failed on Ubuntu14.04

### ISSUE THREAD

**Issue by jingweiz** [deepmind/lab#35]
Hey,
I'm trying to build lab on my machine by ```bazel build :deepmind_lab.so --define headless=glx --verbose_failures``` but failed so far. I came across these errors so far:

1. ```"mount" permission denied```
fixed by: adding ```build --spawn_strategy=standalone``` to ```/etc/bazel.bazelrc```
2. ```python/dmlab_module.c:29:31: fatal error: numpy/arrayobject.h: No such file or directory```
fixed by: adding the following to ```copt``` in ```BUILD```: ```"-I/usr/local/lib/python2.7/dist-packages/numpy/core/include",```
3. ```configure: error: cannot run C compiled programs.```
have no clue how to fix... below I paste the complete error message below:
```
INFO: Found 1 target...
ERROR: /home/zhang/.cache/bazel/_bazel_zhang/2f9f084266361be2ea70187ad5c14f49/external/glib_archive/BUILD:1:1: Executing genrule @glib_archive//:gen_configure failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '12104' is supported by ustar format... yes
checking whether GID '1371' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/home/zhang/.cache/bazel/_bazel_zhang/2f9f084266361be2ea70187ad5c14f49/execroot/lab':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Target //:deepmind_lab.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.759s, Critical Path: 3.14s
```

I don't have any experience with bazel so I've got really no clue as how to fix it, any help would be appreciated!
My compiler: ```gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5```

Thanks in advance!

**Comment by tkoeppe** [comment]
Did you install the Numpy development headers? See https://github.com/deepmind/lab/blob/master/docs/build.md for details.

**Comment by jingweiz** [comment]
Hey,
thanks for the reply!
Yes I was following that more detailed instruction and did:
```sudo apt-get install python-dev python-numpy``` if that's what you mean?
And also somehow I'm now getting error 2 again: 
If I modify the the cops in BUILD for deepmind_lab.so as follows:
```
    copts = [
        "-fno-strict-aliasing",  ## ick ick ick
        "-std=c99",
        "-DDEEPMIND_LAB_MODULE_RUNFILES_DIR",
        "-I/usr/local/lib/python2.7/dist-packages/numpy/core/include",
    ],
```
then I'm now getting: ```/BUILD:986:1: in cc_binary rule //:deepmind_lab.so: The include path '/usr/local/lib/python2.7/dist-packages/numpy/core/include' references a path outside of the execution root.```
If I delete the numpy include path then I'm getting again:  ```python/dmlab_module.c:29:31: fatal error: numpy/arrayobject.h: No such file or directory```

There must be sth wrong with my python packages cos yesterday my tensorflow is also not working:
when I do ```import tensorflow``` I'm getting:
```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 106, in <module>
    from tensorflow.python.platform import test
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/test.py", line 81, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
  File "/usr/local/lib/python2.7/dist-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 71, in <module>
    _v = VersionInfo('mock').semantic_version()
AttributeError: 'VersionInfo' object has no attribute 'semantic_version'
```
and reinstalling or upgrading ```mock``` does not seem to help.
Should these errors be related?


My python configurations:
```
python --version
Python 2.7.6
```
```
>>> numpy.version.version
'1.12.0'
>>> numpy.get_include()
'/usr/local/lib/python2.7/dist-packages/numpy/core/include'
```

**Comment by tkoeppe** [comment]
Hm, is it `python-numpy` or `python-numpy-dev`? I have a feeling you may need the numpy headers, too. Maybe the documentation is wrong about that.

**Comment by jingweiz** [comment]
Hey,
I tried to do ```sudo apt-get install python-numpy-dev``` but this is what I get:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-numpy' instead of 'python-numpy-dev'
python-numpy is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by tkoeppe** [comment]
I'm not sure what's going on. You definitely cannot add rogue `-I` flags to the `copts`, since Bazel only performs hermetic builds. You'll need to provide (or modify) the external dependencies through the Bazel workspace mechanism, see the `WORKSPACE` file.

**Comment by frankcarey** [comment]
The Dockerfile builds in #24 on 14.04, so it's not that. You might look at that Dockerfile script though to see exactly what it does for all the dependencies.

**Comment by tkoeppe** [comment]
I'm not sure there's anything meaningful we can add here. Please feel free to reopen with more specific information.
